server:
  port: 9202
  servlet:
    context-path: /api/${starpivot.api.version}

spring:
  application:
    name: starpivot-file
  config:
    import:
      - optional:classpath:application-nacos.yml
      - optional:nacos:common-config.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:oss-config.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
