server:
  port: 9204
  servlet:
    context-path: /api/${starpivot.api.version}

spring:
  application:
    name: starpivot-monitor
  config:
    import:
      - optional:classpath:application-nacos.yml
      - optional:nacos:common-config.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:${spring.application.name}.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3307/star_pivot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

starpivot:
  api:
    version: ${API_VERSION:v1}
  security:
    authority-strategy: menu-permission
